# Generated by Django 6.1.1 on 2026-09-26 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookstore", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="cover_image",
        ),
    ]
